# Generated by Django 5.1.15 on 2026-06-19 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_content', models.TextField(blank=True, default='# 关于我们\n\n在这里写点关于你和这个网站的故事吧。支持 **Markdown** 语法。', help_text='支持 Markdown')),
                ('contact_email', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_wechat', models.CharField(blank=True, default='', max_length=100)),
                ('crisis_hotline', models.CharField(blank=True, default='12356', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '网站设置',
            },
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='moodentry',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'date'), name='uniq_user_date'),
        ),
    ]
