# Generated by Django 5.1.15 on 2026-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_alter_moodentry_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilibiliVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(help_text='B站视频完整链接', max_length=400)),
                ('moods', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_bilibili',
            field=models.CharField(blank=True, default='', help_text='B站主页完整链接，如 https://space.bilibili.com/xxxxx', max_length=300),
        ),
    ]
