# Generated by Django 5.1.15 on 2026-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bilibilivideo_sitesettings_contact_bilibili'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-date', 'at']},
        ),
        migrations.RemoveConstraint(
            model_name='moodentry',
            name='uniq_user_date',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='这条情绪的记录时刻（用于一天内多条排序）', null=True),
        ),
    ]
