# Generated by Django 5.1.15 on 2026-07-01 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_moodentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tip', '心理学小知识'), ('activity', '舒缓建议'), ('music', '音乐链接'), ('video', '视频链接')], max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(help_text='小知识/建议的正文，或音乐/视频的链接')),
                ('moods', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending_ai', '待AI审核'), ('pending_admin', '待管理员复审'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending_ai', max_length=16)),
                ('ai_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('language', models.CharField(blank=True, default='zh', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
