# Generated by Django 5.1.15 on 2026-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usercontribution_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disclaimer_content',
            field=models.TextField(blank=True, default='', help_text='免责声明正文，支持 Markdown。留空则用内置默认版本。'),
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='audio',
            field=models.FileField(blank=True, help_text='音乐投稿的音频文件', null=True, upload_to='user_music/'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='content',
            field=models.TextField(blank=True, default='', help_text='小知识/建议的正文，或视频链接'),
        ),
    ]
