# Generated by Django 6.0.7 on 2026-07-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_disclaimer_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontribution',
            name='source',
            field=models.CharField(blank=True, default='', help_text='小知识的出处/作者', max_length=200),
        ),
    ]
