# Generated by Django 5.1.15 on 2026-07-26 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def gen_unique_uuids(apps, schema_editor):
    """给存量心情记录逐条生成不同的 uuid（callable default 在迁移里只会取一个值）。"""
    MoodEntry = apps.get_model("core", "MoodEntry")
    for row in MoodEntry.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usercontribution_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='uuid',
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.RunPython(gen_unique_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='moodentry',
            name='uuid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('device', models.CharField(blank=True, default='', help_text='设备备注，如 xiaomi-14 / windows-pc，便于用户管理', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
