# Generated by Django 5.1.15 on 2026-07-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_moodentry_deleted_moodentry_uuid_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='intensity_level',
            field=models.IntegerField(choices=[(1, '略微'), (2, '有点'), (3, '相当'), (4, '十分')], default=2, help_text='情绪强度等级：1=略微 2=有点 3=相当 4=十分'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='intensity_percent',
            field=models.IntegerField(default=50, help_text='情绪强度百分比 0-100，用于 UI 展示'),
        ),
    ]
