# Generated by Django 5.1.15 on 2026-08-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_moodentry_intensity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravity', models.FloatField(default=0.45)),
                ('damping', models.FloatField(default=0.994)),
                ('wall_bounce', models.FloatField(default=0.35)),
                ('merge_boost', models.FloatField(default=1.06)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '小游戏参数',
            },
        ),
    ]
