# Generated by Django 5.1.15 on 2026-08-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gameconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_prompt',
            field=models.TextField(blank=True, default='', help_text='AI 树洞的系统提示词（人设与对话规则），留空则用内置默认版。安全底线部分不可编辑，始终附加。'),
        ),
    ]
