# Generated by Django 5.2.17 on 2026-08-17 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_ai_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_proactive',
            field=models.BooleanField(db_index=True, default=False, help_text='AI 主动发送的消息（非用户触发）'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_weekly_essay',
            field=models.BooleanField(db_index=True, default=False, help_text='是否为每周小结'),
        ),
        migrations.CreateModel(
            name='ProactiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='计划发送日期')),
                ('slot_index', models.IntegerField(help_text='当天第几个时段（0 基），用于区分 2-4 个时段')),
                ('slot_time', models.TimeField(help_text='计划发送的具体时间')),
                ('executed', models.BooleanField(db_index=True, default=False, help_text='是否已执行')),
                ('is_weekly_essay', models.BooleanField(db_index=True, default=False, help_text='是否为每周小结')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'date', 'slot_index'],
                'unique_together': {('user', 'date', 'slot_index')},
            },
        ),
    ]
